# Cleanup: naj bo nekaj malega za varnost
[cleanup]
keep_last = 50

[server]
port = 8080
bind_address = "0.0.0.0"
hostname = "https://podsync-on-render.onrender.com"
# path = "feed"
web_ui = true
tls = false

[storage]
type = "local"
[storage.local]
data_dir = "/app/data"

[tokens]
# API key boš dodal na Render kot environment variable
# youtube = "YOUTUBE_API_KEY"

[feeds]

  [feeds.ID1]
  url = "https://www.youtube.com/channel/UCpVk_OmMmRs0RnmOQTHXyrA"  # zamenjaj s kanalom
  page_size = 50
  update_period = "12h"
  quality = "high"
  format  = "audio"
  max_height = 720
  opml = true
  clean = { keep_last = 10 }
  private_feed = true

  [feeds.ID1.custom]
  title = "Moja Podcast Feed"
  description = "Samodejno iz YouTube kanalov"
  author = "Jaz"
  lang = "sl"
